### ISSUE TITLE
and version 4.0 will be hivebus? :D

### ISSUE THREAD

**Issue by luxus** [YOUSIKI/nichijou#17]
i actually use your config on my mac since version 1 and migrated to version 2 as well.
have you seen https://github.com/tao3k/hivebus ? looks like the successor of hive

**Comment by YOUSIKI** [comment]
Thanks! I will take a look of hivebus.

**Comment by YOUSIKI** [comment]
@luxus I think `snowfall lib` is a better flake framework for system configurations and modules, which I just found some days ago. And I'm trying to migrate to snowfall. Maybe you want to give it a try too. 😊

**Comment by luxus** [comment]
I migrated to srid's config just some days ago https://github.com/srid/nixos-config

This hive stuff got way to complex :) thanks for giving me a update

**Comment by luxus** [comment]
mhh not so happy how the srid config is structured..
i just moved my main desktop to linux (from macOS)
i'm checking out https://github.com/DarkKronicle/nazarick it was a snowfall lib config before and now got based on 
https://github.com/ryan4yin/nix-config
i will close this for now :D but i will follow your journey hehe

**Comment by luxus** [comment]
i will stay with [srid/nixos-config](https://github.com/srid/nixos-config) after years finally a very good "config framework"
